language: c
sudo: false
compiler:
  - clang
  - gcc
# Try to check out a branch of the same name from the snowball-data repo
# sibling of this snowball repo, so that PRs requiring changes to both can be
# CI tested.  If that fails, just clone the standard repo.
before_install:
  - ls -l
  - git clone --depth=1 -b "`git branch --color=never --contains|cut -d' ' -f2-`" "`git config remote.origin.url|sed 's,\(.*/snowball\>\),\1-data,'`" snowball-data || git clone --depth=1 https://github.com/snowballstem/snowball-data.git
script:
  - ls -l
  - make && echo "NOW TO CHECK" && make check STEMMING_DATA=snowball-data
